/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author geova
 */
public class MainView extends javax.swing.JFrame {

    public MainView() {
        initComponents();

    }

    public JComboBox<String> getDataOptionsCB() {
        return dataOptionsCB;
    }

    public JTable getDataTable() {
        return dataTable;
    }

    public JComboBox<String> getFiltersOptionsCB() {
        return filtersOptionsCB;
    }

    public JPanel getFiltersPanel() {
        return filterPanel;
    }

    public JButton getClearBtn() {
        return clearBtn;
    }

    public JButton getExecuteBtn() {
        return executeBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        dataOptionsPanel = new javax.swing.JPanel();
        dataOptionsCB = new javax.swing.JComboBox<>();
        lbAlert = new javax.swing.JLabel();
        filtersOptionsPanel = new javax.swing.JPanel();
        filtersOptionsCB = new javax.swing.JComboBox<>();
        lbFilter = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        filtersContainer = new javax.swing.JPanel();
        auxPanel = new javax.swing.JPanel();
        executeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setPreferredSize(new java.awt.Dimension(76, 40));
        menuPanel.setLayout(new java.awt.GridLayout(1, 2));

        lbAlert.setText("Alertas:");

        javax.swing.GroupLayout dataOptionsPanelLayout = new javax.swing.GroupLayout(dataOptionsPanel);
        dataOptionsPanel.setLayout(dataOptionsPanelLayout);
        dataOptionsPanelLayout.setHorizontalGroup(
            dataOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataOptionsCB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        dataOptionsPanelLayout.setVerticalGroup(
            dataOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataOptionsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(dataOptionsPanel);

        lbFilter.setText("Alertas:");

        javax.swing.GroupLayout filtersOptionsPanelLayout = new javax.swing.GroupLayout(filtersOptionsPanel);
        filtersOptionsPanel.setLayout(filtersOptionsPanelLayout);
        filtersOptionsPanelLayout.setHorizontalGroup(
            filtersOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filtersOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtersOptionsCB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        filtersOptionsPanelLayout.setVerticalGroup(
            filtersOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filtersOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtersOptionsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(filtersOptionsPanel);

        getContentPane().add(menuPanel, java.awt.BorderLayout.NORTH);

        dataPanel.setLayout(new java.awt.BorderLayout());

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPanel.setViewportView(dataTable);

        dataPanel.add(scrollPanel, java.awt.BorderLayout.CENTER);

        filtersContainer.setPreferredSize(new java.awt.Dimension(700, 200));
        filtersContainer.setLayout(new java.awt.BorderLayout());

        auxPanel.setPreferredSize(new java.awt.Dimension(700, 40));
        auxPanel.setRequestFocusEnabled(false);

        executeBtn.setText("Ejecutar");
        executeBtn.setBorderPainted(false);

        clearBtn.setText("Limpiar");

        javax.swing.GroupLayout auxPanelLayout = new javax.swing.GroupLayout(auxPanel);
        auxPanel.setLayout(auxPanelLayout);
        auxPanelLayout.setHorizontalGroup(
            auxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auxPanelLayout.createSequentialGroup()
                .addContainerGap(513, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(executeBtn)
                .addGap(23, 23, 23))
        );
        auxPanelLayout.setVerticalGroup(
            auxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auxPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(auxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeBtn)
                    .addComponent(clearBtn))
                .addContainerGap())
        );

        filtersContainer.add(auxPanel, java.awt.BorderLayout.SOUTH);

        filterPanel.setLayout(new java.awt.BorderLayout());
        filtersContainer.add(filterPanel, java.awt.BorderLayout.CENTER);

        dataPanel.add(filtersContainer, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(dataPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auxPanel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> dataOptionsCB;
    private javax.swing.JPanel dataOptionsPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton executeBtn;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel filtersContainer;
    private javax.swing.JComboBox<String> filtersOptionsCB;
    private javax.swing.JPanel filtersOptionsPanel;
    private javax.swing.JLabel lbAlert;
    private javax.swing.JLabel lbFilter;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
